# .github/workflows/loto3tarde.yml
name: Loto3tarde Results

on:
  schedule:
    # Horario verano CL (UTC-3): octubre a marzo
    - cron: "15 21 * 10-12,1-3 *"   # 18:15 CL
    # Horario invierno CL (UTC-4): abril a septiembre
    - cron: "15 22 * 4-9 *"         # 18:15 CL
  workflow_dispatch:                 # permite ejecutar manualmente

jobs:
  ejecutar-loto3tarde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de credenciales
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > creds.json
          echo "Archivo creds.json generado"

      - name: Ejecutar loto3tarde.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python loto3tarde.py --creds creds.json
