name: Loto Predictor

on:
  schedule:
    - cron: "45 13 * * *"   # se ejecuta a las 13:45 UTC
    - cron: "45 17 * * *"   # se ejecuta a las 17:45 UTC
    - cron: "45 20 * * *"   # se ejecuta a las 20:45 UTC
  workflow_dispatch:         # permite lanzarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de credenciales
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > creds.json
          echo "Archivo creds.json generado"

      - name: Entrenar modelos si no existen pesos
        run: |
          if [ ! -f weights_lstm.h5 ] || [ ! -f weights_trans.h5 ]; then
            echo "Pesos no encontrados. Entrenando modelos..."
            python train.py
          else
            echo "Pesos ya existen. Se omite entrenamiento."
          fi

      - name: Ejecutar script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python main.py --creds creds.json
