name: Loto Predictor

on:
  schedule:
    # Horario verano CL (UTC-3): Octubre a Marzo
    - cron: "45 16 * 10-12,1-4 *"  # 13:45 CL
    - cron: "45 20 * 10-12,1-4 *"  # 17:45 CL
    - cron: "45 23 * 10-12,1-4 *"  # 20:45 CL
    # Horario invierno CL (UTC-4): Abril a Septiembre
    - cron: "45 17 * 4-9 *"         # 13:45 CL
    - cron: "45 21 * 4-9 *"         # 17:45 CL
    - cron: "45 0 * 4-9 *"          # 20:45 CL (dÃ­a siguiente)
  workflow_dispatch:                 # permite ejecutar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de credenciales
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > creds.json
          echo "Archivo creds.json generado"

      - name: Entrenar modelos si no existen pesos
        run: |
          if [ ! -f weights_lstm.h5 ] || [ ! -f weights_trans.h5 ]; then
            echo "Pesos no encontrados. Entrenando modelos..."
            python train.py
          else
            echo "Pesos ya existen. Se omite entrenamiento."
          fi

      - name: Ejecutar script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python main.py --creds creds.json
